### ISSUE TITLE
D2 diagrams require width and height (otherwise not showing up)

### ISSUE THREAD

**Issue by Emptyfruit** [ggrossetie/asciidoctor-kroki#413] opened 2023-05-21 09:48 UTC
D2 diagrams received from kroki.io have 0x0 dimensions, thus not showing up in html. 
The `<img>` is present in html and if i add some height and width to it via browser console the image shows up.

Steps to reproduce:

1. Use Antora (not sure if it is related, but still) with cloud kroki.io
2. Create a test diagram with d2 syntax without any attributes.

### .adoc
```
= Sandbox

== Test D2

[d2]
....
Test: {
  shape: class
  type: enum
  date: datetime
  comment: text

  style: {
    fill: red
  }
}
....
```

### Server response
<img width="1413" alt="изображение" src="https://github.com/ggrossetie/asciidoctor-kroki/assets/14968783/3d7c4800-81c8-4619-b9f9-1101c2913c3c">

### HTML
<img width="830" alt="изображение" src="https://github.com/ggrossetie/asciidoctor-kroki/assets/14968783/73bc8811-63e4-4160-8b8d-fcbad7f69fa3">

Currently, i have to provide `width` and `height` attributes to get proper image.
```
[d2, width=100, height=100]
....
Test: {
  shape: class
}
....
```

If this is an intended behaviour, it would be nice to have a disclaimer in the docs.

**Comment by ggrossetie** [comment] 2023-05-21 11:58
I cannot reproduce it using `<img>`:

![image](https://github.com/ggrossetie/asciidoctor-kroki/assets/333276/155e1e70-fe53-400d-bd4a-a14a47bd5df8)

**Comment by Emptyfruit** [comment] 2023-05-21 12:55
So this is antora's default ui issue?

**Comment by ggrossetie** [comment] 2023-05-21 14:04
No they are created by Asciidoctor and the stylesheet is provided by the Antora default UI.
The only weird thing is that D2 is using an `<svg>` element inside an `<svg>` element:

```html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" d2version="v0.4.1" preserveAspectRatio="xMinYMin meet" viewBox="0 0 444 432" height="100%" width="100%" style="width: 100%; height: 100%;">
<svg id="d2-svg" class="d2-1303036898" width="444" height="432" viewBox="-101 -101 444 432">
<!- ... ->
</svg>
</svg>
```

In my opinion it would be better to set `width="444" height="432"` on the outer `<svg>` element but you will need to make a case for it at: https://github.com/terrastruct/d2/issues

**Comment by ggrossetie** [comment] 2023-05-21 17:58
The following is working fine with the default Asciidoctor stylesheet:

```
image::https://kroki.io/d2/svg/eNolzNEJwCAMBNB_p8gcztEFRK9USKw0KVSKuzfSn4N3cLdBLdIbiPRIHZEyJ1WnjSW0WxwlmWOlVYEX-RRB86XhsbDWNhj_EdFemSNdKK4Z5gc4zx61[]
```

So you could also make a case to improve the default Antora UI. More precisely to account for SVG images that does not have explicit width/height: https://gitlab.com/antora/antora-ui-default/-/issues

Anyway, this "issue" won't be fixed in the Asciidoctor Kroki extension so I'm closing.

**Closed by ggrossetie** 2023-05-21 17:58 UTC
